FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/api/package*.json apps/api/
COPY packages/database/package*.json packages/database/
RUN npm install
COPY . .
RUN npm run db:generate && npm run build -w apps/api
EXPOSE 4000
CMD ["node","apps/api/dist/server.js"]